name: celeb_a_64x64_1
save_path: training_runs/celeb_a_1
training_config:
  seed: 42
  generator_learning_rate: 5.0e-05
  discriminator_learning_rate: 5.0e-05
  batch_size: 64
  epochs: 50
  b1: 0.0
  b2: 0.99
  sample_grid_size: 6
  sample_epochs: 2
  save_epochs: 2
  num_data_workers: 16
  stablization_epochs: 2
  augmentation_config:
    translation:
      enabled: true
      ratio: 0.125
    cutout:
      enabled: true
      ratio: 0.5
    noise:
      enabled: true
      starting_noise: 0.1
      ending_noise: 0
      ending_epoch: 20
  gradient_penalty_weight: 10
  discriminator_repeats: 5
  gradient_accumulation_steps: 1
  num_labels: 40
dataset:
  args:
    root: /home/fireblade2534/Datasets/Images
    split: train
    transform:
    - type: ToTensor
      args: {}
    - type: Resize
      args:
        size:
        - 64
        - 64
        max_size: null
        antialias: true
        interpolation: bilinear
    - type: Normalize
      args:
        mean:
        - 0.5
        - 0.5
        - 0.5
        std:
        - 0.5
        - 0.5
        - 0.5
        inplace: true
  type: CELEBA
resume_path: null
override_resume_options: false
