name: mnist_32x32_1
save_path: training_runs/mnist_1
training_config:
  generator_learning_rate: 0.0001
  discriminator_learning_rate: 0.0001
  batch_size: 128
  epochs: 200
  b1: 0.5
  b2: 0.99
  sample_grid_size: 6
  sample_epochs: 2
  save_epochs: 2
  num_data_workers: 16
  stablization_epochs: 2
  augmentation_config:
    color: false
    translation: true
    cutout: true
  gradient_penalty_weight: 10
  discriminator_repeats: 1
  gradient_accumulation_steps: 1
dataset:
  args:
    root: /home/fireblade2534/Datasets/Images
    train: true
    transform:
    - type: Greyscale
      args:
        num_output_channels: 3
    - type: ToTensor
      args: {}
    - type: Resize
      args:
        size:
        - 32
        - 32
        max_size: null
        antialias: true
        interpolation: bilinear
    - type: Normalize
      args:
        mean:
        - 0.5
        - 0.5
        - 0.5
        std:
        - 0.5
        - 0.5
        - 0.5
        inplace: true
  type: MNIST
resume_path: null
override_resume_options: false
