name: stanford_dogs_64x64_6
save_path: training_runs/stanford_dogs_2
training_config:
  seed: 42
  generator_learning_rate: 9.0e-05
  discriminator_learning_rate: 9.0e-05
  batch_size: 64
  epochs: 200
  b1: 0.5
  b2: 0.99
  sample_grid_size: 6
  sample_epochs: 2
  save_epochs: 4
  num_data_workers: 16
  stablization_epochs: 2
  augmentation_config:
    translation:
      enabled: true
      ratio: 0.125
    cutout:
      enabled: true
      ratio: 0.5
    noise:
      enabled: false
      starting_noise: 0.1
      ending_noise: 0
      ending_epoch: 20
  gradient_penalty_weight: 10
  discriminator_repeats: 4
  gradient_accumulation_steps: 1
  num_labels: 120
dataset:
  args:
    root: /home/fireblade2534/Datasets/Images/Stanford_Dogs
    transform:
    - type: ToTensor
      args: {}
    - type: Resize
      args:
        size:
        - 64
        - 64
        max_size: null
        antialias: true
        interpolation: bilinear
    - type: Normalize
      args:
        mean:
        - 0.5
        - 0.5
        - 0.5
        std:
        - 0.5
        - 0.5
        - 0.5
        inplace: true
  type: ImageFolder
resume_path: null
override_resume_options: false
