name: ffhq_32x32_1
save_path: training_runs/ffhq_1
training_config:
  generator_learning_rate: 1.0e-05
  discriminator_learning_rate: 1.0e-05
  batch_size: 32
  epochs: 200
  b1: 0.5
  b2: 0.99
  sample_grid_size: 6
  sample_epochs: 1
  save_epochs: 2
  num_data_workers: 16
  stablization_epochs: 2
  augmentation_config:
    color: false
    translation: true
    cutout: true
  gradient_penalty_weight: 10
  discriminator_repeats: 1
  gradient_accumulation_steps: 8
dataset:
  args:
    root: /home/fireblade2534/Datasets/Images/FFHQ
    transform:
    - type: ToTensor
      args: {}
    - type: Resize
      args:
        size:
        - 32
        - 32
        max_size: null
        antialias: true
        interpolation: bilinear
    - type: Normalize
      args:
        mean:
        - 0.5
        - 0.5
        - 0.5
        std:
        - 0.5
        - 0.5
        - 0.5
        inplace: true
  type: ImageFolder
resume_path: null
override_resume_options: false
